name: ci-iptables-bgp-scraper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Build
      run: |
        go build -v
    
    - name: version
      run: echo "::set-output name=version::$(./iptables-bgp-scraper version)"
      id: version
    
    - name: Test
      run: go test 
      
    - name: Tar files
      run: tar -cvf iptables-bgp-scraper.tar iptables-bgp-scraper
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: iptables-bgp-scraper-v${{ steps.version.outputs.version }}
        path: iptables-bgp-scraper.tar

