name: ci-iptables-bgp-scraper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        ls
        go build
        ls
        export VERSION=$(./iptables-bgp-scraper version)
        tar -czf iptables-bgp-scraper-$VERSION.gz iptables-bgp-scraper

    - name: Test
      run: go test 
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: artifact
        path: iptables-bgp-scraper-$VERSION.gz
