---
name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          
      - name: Build
        run: |
          go build -v

      - name: version
        run: echo "::set-output name=version::$(./iptables-bgp-scraper version)"
        id: version

      - name: Test
        run: go test 
        
      - name: Tar files
        run: tar -zcvf iptables-bgp-scraper.tar.gz iptables-bgp-scraper

      - name: Upload a Build Artifact for testing
        if: startsWith(github.ref, 'refs/heads/master') == false
        uses: actions/upload-artifact@v3.1.0
        with:
          name: iptables-bgp-scraper
          path: iptables-bgp-scraper.tar.gz

